import { AXPDataGenerator } from '@acorex-platform/framework-client/core';

export const WATCHES = [
  {
    id: AXPDataGenerator.uuid(),
    name: 'Rolex Submariner',
    brand: 'Rolex',
    category: 'Luxury',
    price: 12500,
    currency: 'USD',
    features: ['Automatic Movement', 'Water Resistant', 'Stainless Steel'],
    colors: ['Black', 'Blue'],
    stock: 5,
    rating: 4.9,
    image:
      'https://www.rolex.com/content/dam/rolex-com/e-billboard/2022-billboards/rolex-submariner/watches/m124060-0001/m124060-0001_2207jva_001_r2.jpg',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Omega Speedmaster Moonwatch',
    brand: 'Omega',
    category: 'Chronograph',
    price: 6800,
    currency: 'USD',
    features: ['Chronograph', 'Moonwatch', 'Stainless Steel'],
    colors: ['Black', 'Silver'],
    stock: 8,
    rating: 4.8,
    image: 'https://www.omegawatches.com/media/catalog/product/s/p/sp_moonwatch_professional_hesalite_42mm_black.jpg',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Apple Watch Series 9',
    brand: 'Apple',
    category: 'Smartwatch',
    price: 399,
    currency: 'USD',
    features: ['Heart Rate Monitor', 'GPS', 'Water Resistant'],
    colors: ['Silver', 'Black', 'Pink'],
    stock: 20,
    rating: 4.7,
    image:
      'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ML733_VW_34FR+watch-case-45-aluminum-midnight-nc_VW_34FR_WF_CO_GEO_US?wid=400&hei=400&fmt=jpeg&qlt=95&.v=1692836728262',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Casio G-Shock GA-2100',
    brand: 'Casio',
    category: 'Sports',
    price: 150,
    currency: 'USD',
    features: ['Shock Resistant', 'Water Resistant', 'Analog-Digital'],
    colors: ['Black', 'Red', 'Blue'],
    stock: 15,
    rating: 4.5,
    image: 'https://casiofanmag.com/wp-content/uploads/2020/04/ga-2100-1a.jpg',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'TAG Heuer Carrera',
    brand: 'TAG Heuer',
    category: 'Luxury',
    price: 4500,
    currency: 'USD',
    features: ['Automatic Movement', 'Chronograph', 'Sapphire Crystal'],
    colors: ['Black', 'Blue'],
    stock: 7,
    rating: 4.6,
    image:
      'https://www.tagheuer.com/dw/image/v2/BBCC_PRD/on/demandware.static/-/Sites-tagheuer-master/default/dw39654641/TAG_Heuer_Carrera_Chronograph_CB5138_FC8300_2022.png',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Seiko Presage',
    brand: 'Seiko',
    category: 'Dress',
    price: 500,
    currency: 'USD',
    features: ['Automatic Movement', 'Sapphire Crystal', 'Leather Strap'],
    colors: ['Brown', 'Black'],
    stock: 12,
    rating: 4.5,
    image: 'https://www.seikowatches.com/-/media/Images/Global-Watch/ProductImage/Presage/SARX077.ashx',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Samsung Galaxy Watch 5',
    brand: 'Samsung',
    category: 'Smartwatch',
    price: 299,
    currency: 'USD',
    features: ['Heart Rate Monitor', 'GPS', 'Wireless Charging'],
    colors: ['Silver', 'Graphite', 'Pink'],
    stock: 18,
    rating: 4.6,
    image:
      'https://images.samsung.com/is/image/samsung/p6pim/levant/sm-r900nzaamea/gallery/levant-galaxy-watch5-sm-r900-434093-sm-r900nzaamea-532004831?$650_519_PNG$',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Tissot PRX',
    brand: 'Tissot',
    category: 'Casual',
    price: 700,
    currency: 'USD',
    features: ['Quartz Movement', 'Stainless Steel', 'Water Resistant'],
    colors: ['Blue', 'Silver', 'Green'],
    stock: 9,
    rating: 4.7,
    image: 'https://www.tissotwatches.com/media/catalog/product/T/1/T137_410_11_041_00_R.png',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Fossil Gen 6',
    brand: 'Fossil',
    category: 'Smartwatch',
    price: 279,
    currency: 'USD',
    features: ['Wear OS', 'Heart Rate Monitor', 'Fast Charging'],
    colors: ['Black', 'Brown'],
    stock: 25,
    rating: 4.3,
    image:
      'https://www.fossil.com/on/demandware.static/-/Sites-fossil-master-catalog/default/dw2fc139e7/images/ES5250_main.jpg',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Garmin Fenix 7',
    brand: 'Garmin',
    category: 'Outdoor',
    price: 699,
    currency: 'USD',
    features: ['GPS', 'Heart Rate Monitor', 'Solar Charging'],
    colors: ['Gray', 'Black'],
    stock: 10,
    rating: 4.8,
    image: 'https://static.garmincdn.com/en/products/010-02540-27/g/cf-lg-f24b3e65-8d56-4783-9b99-50dd47c1d022.jpg',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Rolex Submariner Edition 2',
    brand: 'Rolex',
    category: 'Luxury',
    price: 12500,
    currency: 'USD',
    features: ['Automatic Movement', 'Water Resistant', 'Stainless Steel'],
    colors: ['Black', 'Blue'],
    stock: 16,
    rating: 4.9,
    image:
      'https://www.rolex.com/content/dam/rolex-com/e-billboard/2022-billboards/rolex-submariner/watches/m124060-0001/m124060-0001_2207jva_001_r2.jpg',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Omega Speedmaster Moonwatch Edition 2',
    brand: 'Omega',
    category: 'Chronograph',
    price: 6850,
    currency: 'USD',
    features: ['Chronograph', 'Moonwatch', 'Stainless Steel'],
    colors: ['Black', 'Silver'],
    stock: 20,
    rating: 4.8,
    image: 'https://www.omegawatches.com/media/catalog/product/s/p/sp_moonwatch_professional_hesalite_42mm_black.jpg',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Apple Watch Series 9 Edition 2',
    brand: 'Apple',
    category: 'Smartwatch',
    price: 499,
    currency: 'USD',
    features: ['Heart Rate Monitor', 'GPS', 'Water Resistant'],
    colors: ['Silver', 'Black', 'Pink'],
    stock: 13,
    rating: 4.7,
    image:
      'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ML733_VW_34FR+watch-case-45-aluminum-midnight-nc_VW_34FR_WF_CO_GEO_US?wid=400&hei=400&fmt=jpeg&qlt=95&.v=1692836728262',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Casio G-Shock GA-2100 Edition 2',
    brand: 'Casio',
    category: 'Sports',
    price: 300,
    currency: 'USD',
    features: ['Shock Resistant', 'Water Resistant', 'Analog-Digital'],
    colors: ['Black', 'Red', 'Blue'],
    stock: 9,
    rating: 4.5,
    image: 'https://casiofanmag.com/wp-content/uploads/2020/04/ga-2100-1a.jpg',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'TAG Heuer Carrera Edition 2',
    brand: 'TAG Heuer',
    category: 'Luxury',
    price: 4700,
    currency: 'USD',
    features: ['Automatic Movement', 'Chronograph', 'Sapphire Crystal'],
    colors: ['Black', 'Blue'],
    stock: 2,
    rating: 4.6,
    image:
      'https://www.tagheuer.com/dw/image/v2/BBCC_PRD/on/demandware.static/-/Sites-tagheuer-master/default/dw39654641/TAG_Heuer_Carrera_Chronograph_CB5138_FC8300_2022.png',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Seiko Presage Edition 2',
    brand: 'Seiko',
    category: 'Dress',
    price: 500,
    currency: 'USD',
    features: ['Automatic Movement', 'Sapphire Crystal', 'Leather Strap'],
    colors: ['Brown', 'Black'],
    stock: 8,
    rating: 4.5,
    image: 'https://www.seikowatches.com/-/media/Images/Global-Watch/ProductImage/Presage/SARX077.ashx',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Samsung Galaxy Watch 5 Edition 2',
    brand: 'Samsung',
    category: 'Smartwatch',
    price: 349,
    currency: 'USD',
    features: ['Heart Rate Monitor', 'GPS', 'Wireless Charging'],
    colors: ['Silver', 'Graphite', 'Pink'],
    stock: 15,
    rating: 4.6,
    image:
      'https://images.samsung.com/is/image/samsung/p6pim/levant/sm-r900nzaamea/gallery/levant-galaxy-watch5-sm-r900-434093-sm-r900nzaamea-532004831?$650_519_PNG$',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Tissot PRX Edition 2',
    brand: 'Tissot',
    category: 'Casual',
    price: 800,
    currency: 'USD',
    features: ['Quartz Movement', 'Stainless Steel', 'Water Resistant'],
    colors: ['Blue', 'Silver', 'Green'],
    stock: 7,
    rating: 4.7,
    image: 'https://www.tissotwatches.com/media/catalog/product/T/1/T137_410_11_041_00_R.png',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Fossil Gen 6 Edition 2',
    brand: 'Fossil',
    category: 'Smartwatch',
    price: 429,
    currency: 'USD',
    features: ['Wear OS', 'Heart Rate Monitor', 'Fast Charging'],
    colors: ['Black', 'Brown'],
    stock: 4,
    rating: 4.3,
    image:
      'https://www.fossil.com/on/demandware.static/-/Sites-fossil-master-catalog/default/dw2fc139e7/images/ES5250_main.jpg',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Garmin Fenix 7 Edition 2',
    brand: 'Garmin',
    category: 'Outdoor',
    price: 899,
    currency: 'USD',
    features: ['GPS', 'Heart Rate Monitor', 'Solar Charging'],
    colors: ['Gray', 'Black'],
    stock: 10,
    rating: 4.8,
    image: 'https://static.garmincdn.com/en/products/010-02540-27/g/cf-lg-f24b3e65-8d56-4783-9b99-50dd47c1d022.jpg',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Rolex Submariner Edition 3',
    brand: 'Rolex',
    category: 'Luxury',
    price: 12500,
    currency: 'USD',
    features: ['Automatic Movement', 'Water Resistant', 'Stainless Steel'],
    colors: ['Black', 'Blue'],
    stock: 6,
    rating: 4.9,
    image:
      'https://www.rolex.com/content/dam/rolex-com/e-billboard/2022-billboards/rolex-submariner/watches/m124060-0001/m124060-0001_2207jva_001_r2.jpg',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Omega Speedmaster Moonwatch Edition 3',
    brand: 'Omega',
    category: 'Chronograph',
    price: 6850,
    currency: 'USD',
    features: ['Chronograph', 'Moonwatch', 'Stainless Steel'],
    colors: ['Black', 'Silver'],
    stock: 10,
    rating: 4.8,
    image: 'https://www.omegawatches.com/media/catalog/product/s/p/sp_moonwatch_professional_hesalite_42mm_black.jpg',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Apple Watch Series 9 Edition 3',
    brand: 'Apple',
    category: 'Smartwatch',
    price: 499,
    currency: 'USD',
    features: ['Heart Rate Monitor', 'GPS', 'Water Resistant'],
    colors: ['Silver', 'Black', 'Pink'],
    stock: 3,
    rating: 4.7,
    image:
      'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ML733_VW_34FR+watch-case-45-aluminum-midnight-nc_VW_34FR_WF_CO_GEO_US?wid=400&hei=400&fmt=jpeg&qlt=95&.v=1692836728262',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Casio G-Shock GA-2100 Edition 3',
    brand: 'Casio',
    category: 'Sports',
    price: 300,
    currency: 'USD',
    features: ['Shock Resistant', 'Water Resistant', 'Analog-Digital'],
    colors: ['Black', 'Red', 'Blue'],
    stock: 19,
    rating: 4.5,
    image: 'https://casiofanmag.com/wp-content/uploads/2020/04/ga-2100-1a.jpg',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'TAG Heuer Carrera Edition 3',
    brand: 'TAG Heuer',
    category: 'Luxury',
    price: 4700,
    currency: 'USD',
    features: ['Automatic Movement', 'Chronograph', 'Sapphire Crystal'],
    colors: ['Black', 'Blue'],
    stock: 12,
    rating: 4.6,
    image:
      'https://www.tagheuer.com/dw/image/v2/BBCC_PRD/on/demandware.static/-/Sites-tagheuer-master/default/dw39654641/TAG_Heuer_Carrera_Chronograph_CB5138_FC8300_2022.png',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Seiko Presage Edition 3',
    brand: 'Seiko',
    category: 'Dress',
    price: 500,
    currency: 'USD',
    features: ['Automatic Movement', 'Sapphire Crystal', 'Leather Strap'],
    colors: ['Brown', 'Black'],
    stock: 18,
    rating: 4.5,
    image: 'https://www.seikowatches.com/-/media/Images/Global-Watch/ProductImage/Presage/SARX077.ashx',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Samsung Galaxy Watch 5 Edition 3',
    brand: 'Samsung',
    category: 'Smartwatch',
    price: 349,
    currency: 'USD',
    features: ['Heart Rate Monitor', 'GPS', 'Wireless Charging'],
    colors: ['Silver', 'Graphite', 'Pink'],
    stock: 5,
    rating: 4.6,
    image:
      'https://images.samsung.com/is/image/samsung/p6pim/levant/sm-r900nzaamea/gallery/levant-galaxy-watch5-sm-r900-434093-sm-r900nzaamea-532004831?$650_519_PNG$',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Tissot PRX Edition 3',
    brand: 'Tissot',
    category: 'Casual',
    price: 800,
    currency: 'USD',
    features: ['Quartz Movement', 'Stainless Steel', 'Water Resistant'],
    colors: ['Blue', 'Silver', 'Green'],
    stock: 17,
    rating: 4.7,
    image: 'https://www.tissotwatches.com/media/catalog/product/T/1/T137_410_11_041_00_R.png',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Fossil Gen 6 Edition 3',
    brand: 'Fossil',
    category: 'Smartwatch',
    price: 429,
    currency: 'USD',
    features: ['Wear OS', 'Heart Rate Monitor', 'Fast Charging'],
    colors: ['Black', 'Brown'],
    stock: 14,
    rating: 4.3,
    image:
      'https://www.fossil.com/on/demandware.static/-/Sites-fossil-master-catalog/default/dw2fc139e7/images/ES5250_main.jpg',
  },
  {
    id: AXPDataGenerator.uuid(),
    name: 'Garmin Fenix 7 Edition 3',
    brand: 'Garmin',
    category: 'Outdoor',
    price: 899,
    currency: 'USD',
    features: ['GPS', 'Heart Rate Monitor', 'Solar Charging'],
    colors: ['Gray', 'Black'],
    stock: 20,
    rating: 4.8,
    image: 'https://static.garmincdn.com/en/products/010-02540-27/g/cf-lg-f24b3e65-8d56-4783-9b99-50dd47c1d022.jpg',
  },
];

export const CATEGORES = [
  { text: 'Luxury', value: 'Luxury' },
  { text: 'Chronograph', value: 'Chronograph' },
  { text: 'Smartwatch', value: 'Smartwatch' },
  { text: 'Sports', value: 'Sports' },
  { text: 'Dress', value: 'Dress' },
  { text: 'Casual', value: 'Casual' },
  { text: 'Outdoor', value: 'Outdoor' },
];
