import { AXPThemePalette, AXPThemePaletteProvider } from '@acorex-platform/framework-client/themes/shared';

export class AXPRootThemePaletteProvider implements AXPThemePaletteProvider {
  getList(): Promise<AXPThemePalette[]> {
    return Promise.resolve([
      {
        name: 'cosmic-horizon',
        title: 'Cosmic Horizon',
        colors: {
          primary: '#6247aa',
          secondary: '#815ac0',
          success: '#38b2ac',
          warning: '#f6ad55',
          danger: '#e53e3e',
          accents: ['#38b2ac', '#d69e2e', '#3182ce'],
          dark: '#171627',
          light: '#ffffff',
        },
      },
      {
        name: 'ocean-depths',
        title: 'Ocean Depths',
        colors: {
          primary: '#207884',
          secondary: '#e67e22',
          success: '#2ecc71',
          warning: '#f1c40f',
          danger: '#c0392b',
          accents: ['#16616b', '#9b59b6', '#34495e'],
          dark: '#151e22',
          light: '#ffffff',
        },
      },
      {
        name: 'plum-elegance',
        title: 'Plum Elegance',
        colors: {
          primary: '#a4487d',
          secondary: '#e67a54',
          success: '#4aaa7c',
          warning: '#f3a534',
          danger: '#b82d4f',
          accents: ['#7c3661', '#3ba4a0', '#3d4168'],
          dark: '#231f24',
          light: '#ffffff',
        },
      },
      {
        name: 'default',
        title: 'Default',
        colors: {
          primary: '#113b53',
          secondary: '#1a6ab1',
          success: '#2d9c67',
          warning: '#e9a01b',
          danger: '#c02f1d',
          accents: ['#d6a7a6', '#a0897e', '#8bf4d9'],
          dark: '#212427',
          light: '#ffffff',
        },
      },
      {
        name: 'sunset-horizon',
        title: 'Sunset Horizon',
        colors: {
          primary: '#ff6b35',
          secondary: '#e86a58',
          success: '#48a87c',
          warning: '#f7b267',
          danger: '#e94f64',
          accents: ['#f26b5b', '#f7c267', '#de5b7b'],
          dark: '#171219',
          light: '#f2e8e5',
        },
      },
      {
        name: 'golden-dusk',
        title: 'Golden Dusk',
        colors: {
          primary: '#b98e4b',
          secondary: '#e6733d',
          success: '#5eaa67',
          warning: '#f2b100',
          danger: '#a20e3f',
          accents: ['#8e1c65', '#3db8a8', '#36416a'],
          dark: '#303030',
          light: '#ffffff',
        },
      },
      {
        name: 'ocean-breeze',
        title: 'Ocean Breeze',
        colors: {
          primary: '#3498db',
          secondary: '#00bfa5',
          success: '#27ae60',
          warning: '#f39c12',
          danger: '#c0392b',
          accents: ['#5dade2', '#16a085', '#48c9b0'],
          dark: '#1f2b37',
          light: '#ffffff',
        },
      },
      {
        name: 'emerald-forest',
        title: 'Emerald Forest',
        colors: {
          primary: '#2a7d5f',
          secondary: '#4b9e8f',
          success: '#4caf50',
          warning: '#ff9800',
          danger: '#f44336',
          accents: ['#2c3e50', '#8e44ad', '#f39c12'],
          dark: '#131917',
          light: '#f2f8f4',
        },
      },
      {
        name: 'nebula-dream',
        title: 'Nebula Dream',
        colors: {
          primary: '#5e60ce',
          secondary: '#4895ef',
          success: '#06d6a0',
          warning: '#ffd166',
          danger: '#ef476f',
          accents: ['#8338ec', '#ff006e', '#3a86ff'],
          dark: '#161722',
          light: '#ffffff',
        },
      },
      {
        name: 'solare-flare',
        title: 'Solare Flare',
        colors: {
          primary: '#d81159',
          secondary: '#ff6f61',
          success: '#43b57f',
          warning: '#f4a300',
          danger: '#a20e3f',
          accents: ['#8e1c65', '#2bc4b0', '#3a3a89'],
          dark: '#171822',
          light: '#ffffff',
        },
      },
      {
        name: 'safetyminder',
        title: 'Safetyminder',
        colors: {
          primary: '#2196f3',
          secondary: '#ff9800',
          success: '#5cb85c',
          warning: '#f0ad4e',
          danger: '#d9534f',
          accents: ['#b54b78', '#ca6797', '#49c4d3'],
          dark: '#102a43',
          light: '#fafafa',
        },
      },
      {
        name: 'black-carbon',
        title: 'Black Carbon',
        colors: {
          primary: '#1b1a1b',
          secondary: '#232323',
          success: '#4da46e',
          warning: '#d98a2d',
          danger: '#d44747',
          accents: ['#552a80', '#1f7984', '#d6a7a6'],
          dark: '#1c171d',
          light: '#ffffff',
        },
      },
      {
        name: 'coastal-twilight',
        title: 'Coastal Twilight',
        colors: {
          primary: '#1f6c98',
          secondary: '#4e9cc1',
          success: '#2eb82e',
          warning: '#f39c12',
          danger: '#dc3545',
          accents: ['#88c9e7', '#f1e3a2', '#f7aea1'],
          dark: '#1f2b37',
          light: '#f8f9fa',
        },
      },
      {
        name: 'arctic-aurora',
        title: 'Arctic Aurora',
        colors: {
          primary: '#4b6cb7',
          secondary: '#6a85b6',
          success: '#26a69a',
          warning: '#ffb74d',
          danger: '#e57373',
          accents: ['#9575cd', '#64b5f6', '#81c784'],
          dark: '#232834',
          light: '#ffffff',
        },
      },
      {
        name: 'twilight-orchid',
        title: 'Twilight Orchid',
        colors: {
          primary: '#7b4b94',
          secondary: '#9b6b9e',
          success: '#4caf50',
          warning: '#f39c12',
          danger: '#e74c3c',
          accents: ['#c17ecd', '#e8c2ca', '#b4aee8'],
          dark: '#242030',
          light: '#fafafa',
        },
      },
      {
        name: 'cherry-blossom',
        title: 'Cherry Blossom',
        colors: {
          primary: '#d63384',
          secondary: '#f8b4cb',
          success: '#20c997',
          warning: '#fd7e14',
          danger: '#dc3545',
          accents: ['#6f42c1', '#0dcaf0', '#6c757d'],
          dark: '#251821',
          light: '#ffffff',
        },
      },
      {
        name: 'autumn-harvest',
        title: 'Autumn Harvest',
        colors: {
          primary: '#d2691e',
          secondary: '#cd853f',
          success: '#228b22',
          warning: '#daa520',
          danger: '#b22222',
          accents: ['#8b4513', '#4682b4', '#2f4f4f'],
          dark: '#25140e',
          light: '#ffffff',
        },
      },
      {
        name: 'arctic-glacier',
        title: 'Arctic Glacier',
        colors: {
          primary: '#4169e1',
          secondary: '#87ceeb',
          success: '#32cd32',
          warning: '#ffa500',
          danger: '#dc143c',
          accents: ['#483d8b', '#20b2aa', '#708090'],
          dark: '#172028',
          light: '#ffffff',
        },
      },
      {
        name: 'teal-ocean',
        title: 'Teal Ocean',
        colors: {
          primary: '#018b77',
          secondary: '#00a693',
          neutral: '#606c76',
          success: '#2d9c67',
          warning: '#e9a01b',
          danger: '#c02f1d',
          accents: ['#006b5c', '#4db6ac', '#80cbc4'],
          dark: '#131f1c',
          light: '#ffffff',
        },
      },
    ]);
  }
}
